import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About Me',
  description: 'Generated by Quito',
}

const About = () => {
  return (
    <div>About</div>
  )
}

export default About